const branches=[['Chiên Con',28],['Ấu Nhi',23],['Thiếu Nhi',37],['Nghĩa sĩ & Hiệp sĩ',37],['HT–GLV',34]],page=document.getElementById('page');
const classKey={'Lớp Khai Tâm':'kt','Lớp Đến Bàn Tiệc Thánh':'db','Lớp Thêm Sức':'ts','Lớp Sống đạo':'sd','Lớp HT-GLV':'ht'};
const schedule=[
['2026-09-06','Khai giảng năm học','Khai giảng năm học; chào cờ, tổng kết hè, huấn đức và Thánh lễ cầu nguyện cho năm học mới.','','','',''],
['2026-09-06','CN XXIII Mùa Thường Niên','', 'Bài 1: Chúa tặng ban mặt trời, mặt trăng','Bài mở đầu: Em học Giáo lý','Bài mở đầu: Em lớn khôn','Bài 01: Thiên Chúa cho chúng ta nhận biết Ngài'],
['2026-09-13','CN XXIV Mùa Thường Niên','', 'Bài 2: Chúa tặng ban núi cao biển rộng','Bài 01: Thiên Chúa tạo dựng trời và đất','Bài 01: Thiên Chúa sáng tạo và quan phòng','Bài 02: Mạc khải của Thiên Chúa'],
['2026-09-20','CN XXV Mùa Thường Niên','', 'Bài 3: Chúa tặng ban cây xanh hoa đẹp','Bài 02: Thiên Chúa tạo dựng con người','Bài 02: Thiên Chúa tạo dựng con người','Bài 03: Lưu truyền mặc khải của Thiên Chúa'],
['2026-09-27','CN XXVI Mùa Thường Niên','', 'Bài 4: Chúa tặng ban muôn loài muôn vật','Bài 03: Sa ngã','Bài 03: Sa ngã','Bài 04: Thánh Kinh'],
['2026-10-04','CN XXVII Mùa Thường Niên – Mừng kính Đức Mẹ Mân Côi','Chào cờ – Sinh hoạt TNTT – Nhân bản theo từng lớp','','','',''],
['2026-10-11','CN XXVIII Mùa Thường Niên','', 'Bài 5: Chúa dựng nên em giống hình ảnh Chúa','Bài 04: Tôi tin Đức Giêsu Kitô, Con Một Thiên Chúa','Bài 04: Con Thiên Chúa làm người','Bài 05: Con người đáp lại lời Thiên Chúa'],
['2026-10-18','CN XXIX Mùa Thường Niên','', 'Bài 6: Chúa tặng ban cho em Thiên Thần Bản mệnh','Bài 05: Cuộc khổ nạn của Chúa Giêsu','Bài 05: Cuộc sống trần thế của Chúa Giêsu (tiết 1)','Bài 06: Thiên Chúa duy nhất'],
['2026-10-25','CN XXX Mùa Thường Niên','', 'Bài 7: Chúa tặng ban Con Một là Chúa Giêsu','Bài 06: Chúa Giêsu sống lại và lên trời','Bài 05: Cuộc sống trần thế của Chúa Giêsu (tiết 2)','Bài 07: Thiên Chúa là Cha và Con và Thánh Thần'],
['2026-11-01','Lễ Các Thánh Nam Nữ','Chào cờ – Sinh hoạt TNTT – Nhân bản theo từng lớp','','','',''],
['2026-11-08','CN XXXII Mùa Thường Niên','', 'Bài 8: Chúa Giêsu sống và rao giảng Tin mừng','Bài 07: Tôi tin kính Đức Chúa Thánh Thần','Bài 06: Cuộc khổ nạn của Chúa Giêsu','Bài 08: Thiên Chúa – Đấng sáng tạo và quan phòng'],
['2026-11-15','CN XXXIII Mùa Thường Niên','KIỂM TRA GIỮA KÌ I','','','',''],
['2026-11-22','Lễ Chúa Kitô Vua Vũ Trụ','', 'Bài 9: Chúa Giêsu tặng ban Thánh Thể','Bài 08: Thiên Chúa là Cha, Con và Thánh Thần (tiết 1)','Bài 07: Chúa Giêsu sống lại và lên trời','Bài 09: Thiên Chúa tạo dựng con người'],
['2026-11-29','CN I Mùa Vọng – Năm B','', 'Bài 10: Chúa Giêsu chịu chết trên thánh giá','Bài 08: Thiên Chúa là Cha, Con và Thánh Thần (tiết 2)','Bài 08: Chúa Giêsu sẽ đến phán xét','Bài 10: Con Thiên Chúa làm người'],
['2026-12-06','CN II Mùa Vọng','TĨNH TÂM THIẾU NHI MÙA VỌNG','','','',''],
['2027-01-24','CN III Mùa Thường Niên','ÔN TẬP CUỐI HỌC KÌ I','','','',''],
['2027-01-31','CN IV Mùa Thường Niên','KIỂM TRA CUỐI HỌC KÌ I','','','',''],
['2027-06-06','CN X Mùa Thường Niên','ÔN TẬP HỌC KỲ II','','','',''],
['2027-06-13','CN XI Mùa Thường Niên','KIỂM TRA HỌC KỲ II','','','',''],
['2027-09-05','Khai giảng năm học 2027–2028','Khai giảng năm học mới','','','',''],
['2027-11-14','CN XXXIII Mùa Thường Niên','KIỂM TRA GIỮA KÌ I','','','',''],
['2028-01-23','CN III Mùa Thường Niên','ÔN TẬP CUỐI HỌC KÌ I','','','',''],
['2028-02-06','CN V Mùa Thường Niên','KIỂM TRA CUỐI HỌC KÌ I','','','',''],
['2028-06-04','Lễ Chúa Thánh Thần Hiện Xuống','ÔN TẬP HỌC KỲ II','','','',''],
['2028-06-11','Lễ Chúa Ba Ngôi','KIỂM TRA HỌC KỲ II','','','','']];
const examDates={'2026-2027':{gk1:'15/11/2026',ck1:'31/01/2027',gk2:'Chưa có mốc riêng trong lịch',ck2:'13/06/2027'},'2027-2028':{gk1:'14/11/2027',ck1:'06/02/2028',gk2:'Chưa có mốc riêng trong lịch',ck2:'11/06/2028'}};
function setHead(t,s=''){document.getElementById('pageTitle').textContent=t;document.getElementById('pageSubtitle').textContent=s}
function dashboard(){setHead('Tổng quan Xứ đoàn','Năm hoạt động 2026–2028');page.innerHTML=`<div class="hero"><div><h1>Xứ đoàn Đaminh Savio</h1><div class="muted">Giáo xứ Hải Ninh · Hệ thống quản lý tập trung</div></div><span class="pill green">● Hệ thống đang hoạt động</span></div><div class="cards"><div class="card"><div class="metric">159</div><div class="metric-label">Thành viên</div></div><div class="card"><div class="metric">5</div><div class="metric-label">Ngành / nhóm</div></div><div class="card"><div class="metric">5</div><div class="metric-label">Lớp giáo lý</div></div><div class="card"><div class="metric">2026–2028</div><div class="metric-label">Lịch giáo lý</div></div></div><div class="grid-2"><section class="panel"><h2>Thành viên theo ngành</h2>${branches.map(x=>`<div class="row"><span>${x[0]}</span><span class="count">${x[1]}</span></div>`).join('')}</section><section class="panel"><h2>Mốc học tập</h2><div class="row"><span>06/09/2026</span><b>Khai giảng</b></div><div class="row"><span>15/11/2026</span><b>Giữa kỳ I · Năm 1</b></div><div class="row"><span>31/01/2027</span><b>Cuối kỳ I · Năm 1</b></div><div class="row"><span>13/06/2027</span><b>Cuối kỳ II · Năm 1</b></div></section></div>`}
function members(kind='Tất cả thành viên'){setHead('Thành viên',kind);page.innerHTML=`<div class="hero"><div><h1>${kind}</h1><div class="muted">Quản lý hồ sơ, ngành, đội và trạng thái thành viên</div></div><button class="primary">+ Thêm thành viên</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Họ và tên</th><th>Ngành / nhóm</th><th>Đội</th><th>Vai trò</th><th>Trạng thái</th></tr></thead><tbody><tr><td colspan="5" class="empty">Dữ liệu cá nhân hiển thị sau khi đăng nhập và được cấp quyền.</td></tr></tbody></table></div>`}
function catechism(cls,mode='overview'){let label={overview:'Tổng quan',attendance:'Điểm danh',grades:'Điểm số',schedule:'Lịch học',homework:'Bài tập'}[mode];setHead('Giáo lý',`${cls} · ${label}`);page.innerHTML=`<div class="class-banner"><div><h2>${cls}</h2><div>Quản lý lớp trong hai năm học 2026–2028</div></div><button class="primary" onclick="catechism('${cls}','homework')">🔔 Bài tập & thông báo</button></div><div class="tabs"><button class="tab ${mode==='overview'?'active':''}" onclick="catechism('${cls}','overview')">Tổng quan</button><button class="tab ${mode==='schedule'?'active':''}" onclick="catechism('${cls}','schedule')">📅 Lịch học</button><button class="tab ${mode==='attendance'?'active':''}" onclick="catechism('${cls}','attendance')">Điểm danh</button><button class="tab ${mode==='grades'?'active':''}" onclick="catechism('${cls}','grades')">Điểm số</button><button class="tab ${mode==='homework'?'active':''}" onclick="catechism('${cls}','homework')">🔔 Bài tập</button></div>${mode==='attendance'?attendanceView():mode==='grades'?gradeView():mode==='schedule'?scheduleView(cls):mode==='homework'?homeworkView(cls):classOverview(cls)}`}
function classOverview(cls){return `<div class="cards"><div class="card"><div class="metric">2026–27</div><div class="metric-label">Năm 1</div></div><div class="card"><div class="metric">2027–28</div><div class="metric-label">Năm 2</div></div><div class="card"><div class="metric">🔔</div><div class="metric-label">Thông báo bài tập</div></div><div class="card"><div class="metric">📅</div><div class="metric-label">Lịch học theo tuần</div></div></div><div class="panel"><h2>Dành cho đoàn sinh</h2><div class="note">Đoàn sinh vào lớp có thể xem lịch học, bài học sắp tới, lịch kiểm tra, điểm số và bài tập giáo lý viên giao.</div></div>`}
function attendanceView(){return `<div class="toolbar"><input type="date" class="input"><select class="select"><option>Học giáo lý</option><option>Thánh lễ</option><option>Sinh hoạt đoàn</option><option>Học hát</option></select><button class="primary">Tạo buổi điểm danh</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Học viên</th><th>Có mặt</th><th>Đồng phục</th><th>Nề nếp</th><th>Ghi chú</th></tr></thead><tbody><tr><td colspan="5" class="empty">Chọn ngày và tạo buổi điểm danh để bắt đầu.</td></tr></tbody></table></div>`}
function gradeView(){return `<div class="toolbar"><select id="gradeYear" class="select" onchange="updateExamDates()"><option value="2026-2027">Năm 1 · 2026–2027</option><option value="2027-2028">Năm 2 · 2027–2028</option></select><select id="gradeTerm" class="select" onchange="updateExamDates()"><option value="1">Học kỳ I</option><option value="2">Học kỳ II</option></select><button class="primary">+ Thêm điểm thường xuyên</button></div><div id="examDates"></div><div class="table-wrap"><table class="table grade-table"><thead><tr><th>Học viên</th><th>TX 1</th><th>TX 2</th><th>TX 3</th><th>TX 4</th><th>TB thường xuyên</th><th>Giữa kỳ</th><th>Cuối kỳ</th><th>TB học kỳ</th></tr></thead><tbody><tr><td colspan="9" class="empty">Sau khi đăng nhập, giáo lý viên nhập điểm theo từng học viên tại đây.</td></tr></tbody></table></div><div class="footer-note"><b>Mỗi năm có 2 học kỳ.</b> Mỗi học kỳ tách Điểm thường xuyên · Giữa kỳ · Cuối kỳ · Trung bình. Điểm thường xuyên có thể thêm nhiều cột.</div>`}
function updateExamDates(){let y=document.getElementById('gradeYear')?.value||'2026-2027',t=document.getElementById('gradeTerm')?.value||'1',e=examDates[y],g=t==='1'?e.gk1:e.gk2,c=t==='1'?e.ck1:e.ck2,el=document.getElementById('examDates');if(el)el.innerHTML=`<div class="exam-strip"><div><span>Giữa kỳ</span><b>${g}</b></div><div><span>Cuối kỳ</span><b>${c}</b></div><div><span>Năm học</span><b>${y}</b></div></div>`}
function scheduleView(cls){let idx={kt:3,db:4,ts:5,sd:6,ht:-1}[classKey[cls]];setTimeout(()=>updateExamDates(),0);return `<div class="hero"><div><h1>Lịch giáo lý 2026–2028</h1><div class="muted">Dựa trên file Lịch Giáo Lý 2026-2028.xlsx: ngày học, Chúa nhật/lễ, bài học, ôn tập và kiểm tra.</div></div><select class="select" onchange="filterYear(this.value,'${cls}')"><option value="all">Cả 2 năm</option><option value="2026">Năm 1 · 2026–2027</option><option value="2027">Năm 2 · 2027–2028</option></select></div><div id="scheduleTable" class="table-wrap">${renderSchedule(idx,'all')}</div>`}
function renderSchedule(idx,year){let rows=schedule.filter(r=>year==='all'||(year==='2026'?r[0]<'2027-07-01':r[0]>='2027-07-01'));return `<table class="table"><thead><tr><th>Ngày</th><th>Chúa nhật / Lễ</th><th>Bài học của lớp</th><th>Hoạt động / Kiểm tra</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r[0].split('-').reverse().join('/')}</b></td><td>${r[1]}</td><td>${idx>0?(r[idx]||'—'):'Theo kế hoạch lớp HT–GLV'}</td><td>${r[2]||'Học theo chương trình'}</td></tr>`).join('')}</tbody></table>`}
function filterYear(y,cls){let idx={kt:3,db:4,ts:5,sd:6,ht:-1}[classKey[cls]];document.getElementById('scheduleTable').innerHTML=renderSchedule(idx,y)}
function homeworkView(cls){return `<div class="hero"><div><h1>🔔 Bài tập & thông báo</h1><div class="muted">Giáo lý viên giao bài; đoàn sinh đúng lớp xem hạn nộp và nhận thông báo.</div></div><button class="primary" onclick="showHomeworkForm()">+ GLV giao bài tập</button></div><div id="homeworkForm"></div><div class="panel"><h2>Thông báo của ${cls}</h2><div class="empty">Bài tập đã đăng sẽ xuất hiện ở đây và ở nút 🔔 trên thanh trên.</div></div>`}
function showHomeworkForm(){document.getElementById('homeworkForm').innerHTML=`<div class="panel"><h2>Giao bài tập mới</h2><div class="toolbar"><input class="input" placeholder="Tiêu đề bài tập"><input type="date" class="input"><button class="primary">Đăng & thông báo lớp</button></div><textarea class="input" style="width:100%;min-height:100px" placeholder="Nội dung, yêu cầu, trang sách cần làm..."></textarea></div>`}
function finance(){setHead('Tài chính','Thu · Chi · Chương trình · Báo cáo');page.innerHTML=`<div class="hero"><h1>Tài chính</h1><button class="primary">+ Thêm giao dịch</button></div><div class="finance-grid"><div class="card"><div class="money positive">0 ₫</div><div class="metric-label">Tổng thu</div></div><div class="card"><div class="money negative">0 ₫</div><div class="metric-label">Tổng chi</div></div><div class="card"><div class="money">0 ₫</div><div class="metric-label">Số dư</div></div></div>`}
function programs(){setHead('Chương trình','Kế hoạch và hoạt động Xứ đoàn');page.innerHTML=`<div class="hero"><div><h1>Chương trình</h1><div class="muted">Quản lý kế hoạch, hoạt động, người phụ trách và kinh phí</div></div><button class="primary">+ Tạo chương trình</button></div><div class="panel"><div class="empty">Chưa có chương trình được nhập.</div></div>`}
function accounts(g='Tất cả tài khoản'){setHead('Tài khoản',g);page.innerHTML=`<div class="hero"><div><h1>${g}</h1><div class="muted">Tên đăng nhập: họ tên bỏ dấu viết liền + @tntt.hn</div></div><button class="primary">+ Cấp tài khoản</button></div><div class="account-tree"><div class="account-box"><h3>Tài khoản BĐH</h3><div class="note">Quyền điều hành theo chức vụ.</div></div><div class="account-box"><h3>TK Ban Giáo lý</h3><div class="note">Quản lý lớp, lịch, bài tập, điểm danh và điểm.</div></div><div class="account-box"><h3>TK Hội đồng Huynh trưởng & Dự trưởng</h3><div class="note">Theo phần việc được phân công.</div></div><div class="account-box"><h3>TK Đoàn sinh</h3><div class="note">Tách theo từng ngành.</div></div></div>`}
function go(type,a='',b=''){if(type==='dashboard')dashboard();if(type==='members')members(a);if(type==='class')catechism(a,b||'overview');if(type==='finance')finance();if(type==='programs')programs();if(type==='accounts')accounts(a);closeMobile();setTimeout(()=>{if(document.getElementById('examDates'))updateExamDates()},0)}
document.querySelectorAll('.nav-parent').forEach(b=>b.addEventListener('click',()=>b.parentElement.classList.toggle('open')));document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.route,b.dataset.a||'',b.dataset.b||'')));
function closeMobile(){document.querySelector('.sidebar').classList.remove('open');document.querySelector('.mobile-overlay').classList.remove('show')}
document.getElementById('menuToggle').addEventListener('click',()=>{document.querySelector('.sidebar').classList.toggle('open');document.querySelector('.mobile-overlay').classList.toggle('show')});document.querySelector('.mobile-overlay').addEventListener('click',closeMobile);dashboard();