const state={page:'dashboard',title:'Tổng quan Xứ đoàn',subtitle:'Năm hoạt động 2026–2028'};
const branches=[['Chiên Con',28],['Ấu Nhi',23],['Thiếu Nhi',37],['Nghĩa sĩ & Hiệp sĩ',37],['HT–GLV',34]];
const classes=['Lớp Khai Tâm','Lớp Đến Bàn Tiệc Thánh','Lớp Thêm Sức','Lớp Sống đạo','Lớp HT-GLV'];
const page=document.getElementById('page');
function setHead(t,s=''){document.getElementById('pageTitle').textContent=t;document.getElementById('pageSubtitle').textContent=s}
function dashboard(){setHead('Tổng quan Xứ đoàn','Năm hoạt động 2026–2028');page.innerHTML=`<div class="hero"><div><h1>Xứ đoàn Đaminh Savio</h1><div class="muted">Giáo xứ Hải Ninh · Hệ thống quản lý tập trung</div></div><span class="pill green">● Hệ thống đang hoạt động</span></div><div class="cards"><div class="card"><div class="metric">159</div><div class="metric-label">Thành viên</div></div><div class="card"><div class="metric">5</div><div class="metric-label">Ngành / nhóm</div></div><div class="card"><div class="metric">5</div><div class="metric-label">Lớp giáo lý</div></div><div class="card"><div class="metric">K04</div><div class="metric-label">Khóa điều hành</div></div></div><div class="grid-2"><section class="panel"><h2>Thành viên theo ngành</h2>${branches.map(x=>`<div class="row"><span>${x[0]}</span><span class="count">${x[1]}</span></div>`).join('')}</section><section class="panel"><h2>Các phân hệ</h2><div class="row"><span>Thành viên</span><span class="pill blue">Phân ngành</span></div><div class="row"><span>Giáo lý</span><span class="pill blue">Lớp · Điểm danh · Điểm</span></div><div class="row"><span>Tài chính</span><span class="pill blue">Thu · Chi · Thống kê</span></div><div class="row"><span>Tài khoản</span><span class="pill blue">Theo nhóm quyền</span></div></section></div>`}
function members(kind='Tất cả thành viên'){setHead('Thành viên',kind);page.innerHTML=`<div class="hero"><div><h1>${kind}</h1><div class="muted">Quản lý hồ sơ, ngành, đội và trạng thái thành viên</div></div><button class="primary">+ Thêm thành viên</button></div><div class="toolbar"><input class="input" placeholder="Tìm theo họ tên..."><select class="select"><option>Tất cả trạng thái</option><option>Đang sinh hoạt</option><option>Tạm nghỉ</option></select><button class="secondary">Lọc</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Họ và tên</th><th>Ngành / nhóm</th><th>Đội</th><th>Vai trò</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><tr><td colspan="6" class="empty">Dữ liệu cá nhân chỉ hiển thị sau khi đăng nhập và được cấp quyền.</td></tr></tbody></table></div>`}
function catechism(cls,mode='overview'){const label=mode==='attendance'?'Điểm danh':mode==='grades'?'Điểm':'Tổng quan';setHead('Giáo lý',`${cls} · ${label}`);page.innerHTML=`<div class="class-banner"><h2>${cls}</h2><div>Quản lý riêng danh sách lớp, điểm danh và điểm số</div></div><div class="tabs"><button class="tab ${mode==='overview'?'active':''}" onclick="catechism('${cls}','overview')">Tổng quan</button><button class="tab ${mode==='attendance'?'active':''}" onclick="catechism('${cls}','attendance')">Điểm danh</button><button class="tab ${mode==='grades'?'active':''}" onclick="catechism('${cls}','grades')">Điểm</button></div>${mode==='attendance'?attendanceView():mode==='grades'?gradeView():classOverview(cls)}`}
function classOverview(cls){return `<div class="cards"><div class="card"><div class="metric">—</div><div class="metric-label">Học viên</div></div><div class="card"><div class="metric">—</div><div class="metric-label">Buổi đã học</div></div><div class="card"><div class="metric">—</div><div class="metric-label">Tỉ lệ chuyên cần</div></div><div class="card"><div class="metric">—</div><div class="metric-label">Điểm trung bình</div></div></div><div class="panel"><h2>Danh sách lớp</h2><div class="empty">Sẽ tự động lấy học viên đúng lớp sau khi đăng nhập.</div></div>`}
function attendanceView(){return `<div class="toolbar"><input type="date" class="input"><select class="select"><option>Học giáo lý</option><option>Thánh lễ</option><option>Sinh hoạt đoàn</option><option>Học hát</option></select><button class="primary">Tạo buổi điểm danh</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Học viên</th><th>Có mặt</th><th>Đồng phục</th><th>Nề nếp</th><th>Ghi chú</th></tr></thead><tbody><tr><td colspan="5" class="empty">Chọn ngày và tạo buổi điểm danh để bắt đầu.</td></tr></tbody></table></div>`}
function gradeView(){return `<div class="toolbar"><select class="select"><option>Học kỳ I</option><option>Học kỳ II</option></select><button class="primary">+ Tạo cột điểm</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Học viên</th><th>Kiểm tra</th><th>Giữa kỳ</th><th>Cuối kỳ</th><th>Trung bình</th></tr></thead><tbody><tr><td colspan="5" class="empty">Chưa có cột điểm cho lớp này.</td></tr></tbody></table></div>`}
function finance(){setHead('Tài chính','Thu · Chi · Chương trình · Báo cáo');page.innerHTML=`<div class="hero"><div><h1>Tài chính</h1><div class="muted">Theo dõi theo ngày, tháng, quý, năm và từng chương trình</div></div><button class="primary">+ Thêm giao dịch</button></div><div class="finance-grid"><div class="card"><div class="money positive">0 ₫</div><div class="metric-label">Tổng thu</div></div><div class="card"><div class="money negative">0 ₫</div><div class="metric-label">Tổng chi</div></div><div class="card"><div class="money">0 ₫</div><div class="metric-label">Số dư</div></div></div><div class="toolbar"><select class="select"><option>Tháng này</option><option>Quý này</option><option>Năm nay</option></select><select class="select"><option>Tất cả chương trình</option></select><button class="secondary">Xuất báo cáo</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Ngày</th><th>Loại</th><th>Nội dung</th><th>Chương trình</th><th>Số tiền</th><th>Người nhập</th></tr></thead><tbody><tr><td colspan="6" class="empty">Chưa có giao dịch.</td></tr></tbody></table></div>`}
function programs(){setHead('Chương trình','Kế hoạch và hoạt động Xứ đoàn');page.innerHTML=`<div class="hero"><div><h1>Chương trình</h1><div class="muted">Quản lý kế hoạch, hoạt động, người phụ trách và kinh phí</div></div><button class="primary">+ Tạo chương trình</button></div><div class="panel"><h2>Danh sách chương trình</h2><div class="empty">Chưa có chương trình được nhập.</div></div>`}
function accounts(group='Tất cả'){setHead('Tài khoản',group);page.innerHTML=`<div class="hero"><div><h1>${group}</h1><div class="muted">Tên đăng nhập: họ tên bỏ dấu viết liền + @tntt.hn</div></div><button class="primary">+ Cấp tài khoản</button></div><div class="account-tree"><div class="account-box"><h3>Tài khoản BĐH</h3><div class="note">Quyền điều hành theo chức vụ được phân công.</div></div><div class="account-box"><h3>TK Ban Giáo lý</h3><div class="note">Quản lý lớp, điểm danh và điểm theo quyền.</div></div><div class="account-box"><h3>TK Hội đồng Huynh trưởng & Dự trưởng</h3><div class="note">Quản lý phần việc và thành viên được giao.</div></div><div class="account-box"><h3>TK Đoàn sinh</h3><div class="note">Tách theo Chiên Con · Ấu Nhi · Thiếu Nhi · Nghĩa Sĩ · Hiệp Sĩ.</div></div></div><div class="footer-note">Các tài khoản có tên trùng nhau sẽ cần quy tắc phân biệt riêng để tránh trùng địa chỉ đăng nhập.</div>`}
function go(type,arg1='',arg2=''){document.querySelectorAll('[data-route]').forEach(b=>b.classList.remove('active'));if(type==='dashboard')dashboard();if(type==='members')members(arg1);if(type==='class')catechism(arg1,arg2||'overview');if(type==='finance')finance();if(type==='programs')programs();if(type==='accounts')accounts(arg1||'Tất cả tài khoản');closeMobile()}
document.querySelectorAll('.nav-parent').forEach(b=>b.addEventListener('click',()=>b.parentElement.classList.toggle('open')));document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.route,b.dataset.a||'',b.dataset.b||'')));
function closeMobile(){document.querySelector('.sidebar').classList.remove('open');document.querySelector('.mobile-overlay').classList.remove('show')}
document.getElementById('menuToggle').addEventListener('click',()=>{document.querySelector('.sidebar').classList.toggle('open');document.querySelector('.mobile-overlay').classList.toggle('show')});document.querySelector('.mobile-overlay').addEventListener('click',closeMobile);dashboard();