(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const isAdmin=()=>window.hasRole&&hasRole('admin');
window.openMemberProfile=async id=>{if(!window.sb)return;const {data:m,error}=await sb.from('members').select('*').eq('id',id).single();if(error)return alert(error.message);let modal=document.getElementById('memberAdminModal');if(!modal){modal=document.createElement('div');modal.id='memberAdminModal';modal.className='auth-overlay';document.body.appendChild(modal)}const field=(label,key,type='text')=>`<label>${label}<input class="input" data-member-field="${key}" type="${type}" value="${esc(m[key]||'')}" ${isAdmin()?'':'disabled'}></label>`;modal.innerHTML=`<div class="auth-card" style="max-width:760px"><button class="auth-close" onclick="memberAdminModal.remove()">×</button><h2>Hồ sơ đoàn sinh</h2><div class="admin-form-grid">${field('Tên thánh','saint_name')}${field('Họ và tên','full_name')}${field('Ngày sinh','dob','date')}${field('Giới tính','gender')}${field('SĐT đoàn sinh','phone')}${field('Tên phụ huynh','parent_name')}${field('SĐT phụ huynh','parent_phone')}${field('Ngành','branch')}${field('Đội','team')}${field('Vai trò','team_role')}${field('Lớp giáo lý','catechism_class')}${field('Trạng thái','status')}</div><label>Ghi chú<textarea class="input" data-member-field="note" ${isAdmin()?'':'disabled'}>${esc(m.note||'')}</textarea></label>${isAdmin()?`<div class="auth-actions"><button class="primary" onclick="saveMemberProfile('${id}')">💾 Lưu cập nhật</button><button class="secondary" onclick="memberAdminModal.remove()">Đóng</button></div>`:'<p class="muted">Bạn chỉ có quyền xem hồ sơ này.</p>'}</div>`};
window.saveMemberProfile=async id=>{if(!isAdmin())return alert('Chỉ Admin được sửa hồ sơ.');const patch={};document.querySelectorAll('#memberAdminModal [data-member-field]').forEach(x=>patch[x.dataset.memberField]=x.value.trim()||null);const {error}=await sb.from('members').update(patch).eq('id',id);if(error)return alert(error.message);alert('Đã cập nhật hồ sơ đoàn sinh.');document.getElementById('memberAdminModal')?.remove();document.querySelector('[data-route="members"].active')?.click()};
function enhance(){const page=document.getElementById('page');if(!page||document.getElementById('pageTitle')?.textContent!=='Thành viên')return;const table=page.querySelector('.table');if(!table||table.dataset.memberEnhanced)return;table.dataset.memberEnhanced='1';const ths=table.querySelectorAll('thead th');if(ths.length){const head=table.querySelector('thead tr');['Tên phụ huynh','SĐT phụ huynh','Thao tác'].forEach(t=>{const th=document.createElement('th');th.textContent=t;head.appendChild(th)})}
 // Re-fetch visible member rows so parent data is shown without exposing it to unauthenticated users.
 (async()=>{const names=[...table.querySelectorAll('tbody tr td:first-child b')].map(x=>x.textContent.trim()).filter(Boolean);if(!names.length)return;const {data}=await sb.from('members').select('id,full_name,parent_name,parent_phone').in('full_name',names);const map=new Map((data||[]).map(x=>[x.full_name,x]));[...table.querySelectorAll('tbody tr')].forEach(r=>{const name=r.querySelector('td:first-child b')?.textContent.trim(),m=map.get(name);if(!m)return;const p=document.createElement('td');p.textContent=m.parent_name||'—';const ph=document.createElement('td');ph.textContent=m.parent_phone||'—';const a=document.createElement('td');a.innerHTML=`<button class="secondary" onclick="openMemberProfile('${m.id}')">${isAdmin()?'✏️ Sửa':'👁 Xem'}</button>`;r.append(p,ph,a)})})()}
const mo=new MutationObserver(()=>setTimeout(enhance,50));document.addEventListener('DOMContentLoaded',()=>{const p=document.getElementById('page');if(p)mo.observe(p,{childList:true,subtree:true});setTimeout(enhance,500)});window.addEventListener('tntt-auth-changed',()=>setTimeout(enhance,200));
})();