let currentCatechismClass='';
const originalCatechism=window.catechism;
window.catechism=function(cls,mode='overview'){currentCatechismClass=cls;return originalCatechism(cls,mode)};
function getHomework(){try{return JSON.parse(localStorage.getItem('tntt_homework')||'[]')}catch{return []}}
function setHomework(items){localStorage.setItem('tntt_homework',JSON.stringify(items));refreshNotificationCount()}
function refreshNotificationCount(){const c=document.getElementById('notificationCount');if(!c)return;const n=getHomework().length;c.textContent=n;c.style.display=n?'grid':'none'}
function openNotificationPanel(){document.querySelector('.notification-panel')?.remove();const items=getHomework().slice().reverse();const p=document.createElement('div');p.className='notification-panel';p.innerHTML=`<div class="notification-panel-head"><b>🔔 Thông báo bài tập</b><button onclick="this.closest('.notification-panel').remove()">×</button></div>${items.length?items.map(x=>`<div class="notification-item"><b>${x.className}</b><div>${x.title}</div><small>${x.due?`Hạn nộp: ${x.due}`:'Không đặt hạn'}</small></div>`).join(''):'<div class="empty">Chưa có thông báo bài tập.</div>'}`;document.body.appendChild(p)}
window.showHomeworkForm=function(){const cls=currentCatechismClass||'Lớp giáo lý';const host=document.getElementById('homeworkForm');if(!host)return;host.innerHTML=`<div class="panel"><h2>Giao bài tập mới</h2><div class="toolbar"><input id="hwTitle" class="input" placeholder="Tiêu đề bài tập"><input id="hwDue" type="date" class="input"></div><textarea id="hwContent" class="input" style="width:100%;min-height:100px" placeholder="Nội dung, yêu cầu, trang sách cần làm..."></textarea><div class="toolbar" style="margin-top:12px"><button class="primary" onclick="publishHomework()">Đăng & thông báo lớp</button><button class="secondary" onclick="document.getElementById('homeworkForm').innerHTML=''">Hủy</button></div><div class="footer-note">Khi hệ thống tài khoản GLV được kích hoạt đầy đủ, quyền đăng bài sẽ chỉ dành cho Giáo lý viên phụ trách lớp.</div></div>`}
window.publishHomework=function(){const title=document.getElementById('hwTitle')?.value.trim();if(!title){alert('Nhập tiêu đề bài tập.');return}const content=document.getElementById('hwContent')?.value.trim()||'';const due=document.getElementById('hwDue')?.value||'';const cls=currentCatechismClass||'Lớp giáo lý';const items=getHomework();items.push({id:Date.now(),className:cls,title,content,due,createdAt:new Date().toISOString()});setHomework(items);if('Notification'in window){if(Notification.permission==='default')Notification.requestPermission();if(Notification.permission==='granted')new Notification(`Bài tập mới · ${cls}`,{body:title})}window.catechism(cls,'homework');setTimeout(()=>{const panel=document.querySelector('.panel h2');},0)};
document.getElementById('notificationBtn')?.addEventListener('click',openNotificationPanel);refreshNotificationCount();