(()=>{
const P=()=>document.getElementById('page');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const noLogin=()=>`<div class="login-card"><h2>🔐 Cần đăng nhập</h2><p class="muted">Nội dung này chỉ hiển thị cho tài khoản Xứ đoàn đã được cấp quyền.</p><button class="primary" onclick="authModal('login')">Đăng nhập</button><button class="secondary" style="margin-left:8px" onclick="authModal('signup')">Kích hoạt tài khoản</button></div>`;
async function clsId(name){const {data}=await sb.from('classes').select('id').eq('name',name).maybeSingle();return data?.id||null}
async function clsMembers(name){const id=await clsId(name);if(!id)return[];const {data,error}=await sb.from('class_members').select('member_id,members(id,full_name,branch,team,team_role,status)').eq('class_id',id).eq('status','active');if(error)return[];return (data||[]).map(x=>x.members).filter(Boolean).sort((a,b)=>a.full_name.localeCompare(b.full_name,'vi'))}
function roleWrite(){return hasRole('bdh')||hasRole('giao_ly_vien')}

window.members=async function(kind='Tất cả thành viên'){
 setHead('Thành viên',kind); if(!requireLogin()){P().innerHTML=noLogin();return}
 let q=sb.from('members').select('id,full_name,saint_name,dob,gender,branch,team,team_role,member_type,status').order('full_name');
 if(kind==='Chiên Con'||kind==='Ấu Nhi'||kind==='Thiếu Nhi')q=q.eq('branch',kind);
 if(kind==='Nghĩa Sĩ'||kind==='Hiệp Sĩ')q=q.eq('branch','Nghĩa sĩ & Hiệp sĩ');
 if(kind==='Dự trưởng')q=q.ilike('member_type','%Dự trưởng%');
 if(kind==='Giáo lý viên')q=q.ilike('member_type','%GLV%');
 if(kind==='Huynh trưởng')q=q.eq('branch','HT-GLV').ilike('member_type','%HT%');
 if(kind==='Ban Điều Hành')q=q.eq('branch','HT-GLV').or('team_role.ilike.%XĐT%,team_role.ilike.%Thư Ký%,team_role.ilike.%Thủ Quỹ%,team_role.ilike.%Phó Nội Vụ%,team_role.ilike.%Phó Ngoại Vụ%');
 const {data,error}=await q; if(error){P().innerHTML=`<div class="panel"><h2>Không có quyền xem danh sách này</h2><div class="note">${esc(error.message)}</div></div>`;return}
 P().innerHTML=`<div class="hero"><div><h1>${esc(kind)}</h1><div class="muted">${data?.length||0} hồ sơ</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Họ và tên</th><th>Ngày sinh</th><th>Ngành</th><th>Đội</th><th>Vai trò</th><th>Trạng thái</th></tr></thead><tbody>${(data||[]).map(m=>`<tr><td><b>${esc(m.full_name)}</b></td><td>${m.dob?new Date(m.dob+'T00:00').toLocaleDateString('vi-VN'):'—'}</td><td>${esc(m.branch||'—')}</td><td>${esc(m.team||'—')}</td><td>${esc(m.team_role||m.member_type||'Thành viên')}</td><td><span class="pill green">${esc(m.status||'Đang sinh hoạt')}</span></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Không có dữ liệu.</td></tr>'}</tbody></table></div>`;
};

window.catechism=async function(name,mode='overview'){
 const labels={overview:'Tổng quan',schedule:'Lịch học',attendance:'Điểm danh',grades:'Điểm số',homework:'Bài tập'};setHead('Giáo lý',`${name} · ${labels[mode]}`);
 if(!requireLogin()){P().innerHTML=noLogin();return}
 P().innerHTML=`<div class="class-banner"><div><h2>${esc(name)}</h2><div>Năm học 2026–2028 · dữ liệu thật</div></div>${roleWrite()?`<button class="primary" onclick="catechism('${name}','homework')">🔔 Giao bài & thông báo</button>`:''}</div><div class="tabs"><button class="tab ${mode==='overview'?'active':''}" onclick="catechism('${name}','overview')">Tổng quan</button><button class="tab ${mode==='schedule'?'active':''}" onclick="catechism('${name}','schedule')">📅 Lịch học</button><button class="tab ${mode==='attendance'?'active':''}" onclick="catechism('${name}','attendance')">Điểm danh</button><button class="tab ${mode==='grades'?'active':''}" onclick="catechism('${name}','grades')">Điểm số</button><button class="tab ${mode==='homework'?'active':''}" onclick="catechism('${name}','homework')">🔔 Bài tập</button></div><div id="classBody"><div class="empty">Đang tải dữ liệu…</div></div>`;
 const body=document.getElementById('classBody');
 if(mode==='overview')body.innerHTML=await realClassOverview(name);
 if(mode==='schedule')body.innerHTML=await realSchedule(name);
 if(mode==='attendance')body.innerHTML=await realAttendance(name);
 if(mode==='grades')body.innerHTML=await realGrades(name);
 if(mode==='homework')body.innerHTML=await realHomework(name);
};
async function realClassOverview(name){const ms=await clsMembers(name);const id=await clsId(name);const [{count:sessions},{count:hw}]=await Promise.all([sb.from('attendance_sessions').select('*',{count:'exact',head:true}).eq('class_id',id),sb.from('homework_assignments').select('*',{count:'exact',head:true}).eq('class_id',id).eq('published',true)]);return `<div class="cards"><div class="card"><div class="metric">${ms.length}</div><div class="metric-label">Học viên</div></div><div class="card"><div class="metric">${sessions||0}</div><div class="metric-label">Buổi điểm danh</div></div><div class="card"><div class="metric">${hw||0}</div><div class="metric-label">Bài tập</div></div><div class="card"><div class="metric">2</div><div class="metric-label">Năm học</div></div></div><div class="panel"><h2>Danh sách lớp</h2>${ms.map(m=>`<div class="row"><span>${esc(m.full_name)}</span><span class="muted">${esc(m.team_role||m.team||'Học viên')}</span></div>`).join('')||'<div class="empty">Không có quyền xem toàn bộ danh sách hoặc lớp chưa có học viên.</div>'}</div>`}
async function realSchedule(name){const {data,error}=await sb.from('catechism_schedule').select('academic_year,session_date,liturgical_day,common_activity,lesson').eq('class_name',name).order('session_date');if(error)return `<div class="panel">${esc(error.message)}</div>`;return `<div class="toolbar"><select id="realScheduleYear" class="select" onchange="document.querySelectorAll('[data-syear]').forEach(r=>r.style.display=this.value==='all'||r.dataset.syear===this.value?'':'none')"><option value="all">Cả 2 năm</option><option value="2026-2027">Năm 1 · 2026–2027</option><option value="2027-2028">Năm 2 · 2027–2028</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>Ngày</th><th>Chúa nhật / Lễ</th><th>Bài học</th><th>Hoạt động chung</th></tr></thead><tbody>${(data||[]).map(r=>`<tr data-syear="${r.academic_year}"><td><b>${new Date(r.session_date+'T00:00').toLocaleDateString('vi-VN')}</b></td><td>${esc(r.liturgical_day||'')}</td><td>${esc(r.lesson||'—')}</td><td>${esc(r.common_activity||'')}</td></tr>`).join('')}</tbody></table></div>`}

async function realHomework(name){const id=await clsId(name),{data,error}=await sb.from('homework_assignments').select('id,title,content,due_date,created_at').eq('class_id',id).eq('published',true).order('created_at',{ascending:false});if(error)return `<div class="panel">${esc(error.message)}</div>`;return `${roleWrite()?`<div class="panel homework-compose"><h2>Giao bài tập mới</h2><div class="toolbar"><input id="hwTitle" class="input" placeholder="Tiêu đề bài tập"><input id="hwDue" type="date" class="input"></div><textarea id="hwContent" class="input" style="width:100%;min-height:95px" placeholder="Nội dung, yêu cầu, trang sách cần làm…"></textarea><div style="margin-top:10px"><button class="primary" onclick="saveHomework('${name}')">Đăng & thông báo cho lớp</button></div></div>`:''}<div class="assignment-list">${(data||[]).map(h=>`<div class="assignment-card"><div><span class="pill blue">🔔 Bài tập</span><h3>${esc(h.title)}</h3><div>${esc(h.content||'')}</div></div><div class="due"><small>Hạn nộp</small><b>${h.due_date?new Date(h.due_date+'T00:00').toLocaleDateString('vi-VN'):'Không đặt'}</b></div></div>`).join('')||'<div class="panel empty">Chưa có bài tập.</div>'}</div>`}
window.saveHomework=async function(name){const title=document.getElementById('hwTitle').value.trim(),content=document.getElementById('hwContent').value.trim(),due=document.getElementById('hwDue').value;if(!title)return alert('Nhập tiêu đề bài tập.');const id=await clsId(name);const {error}=await sb.from('homework_assignments').insert({class_id:id,title,content,due_date:due||null,published:true,created_by:TNTT.account?.member_id||null});if(error)return alert(error.message);alert('Đã giao bài và gửi thông báo cho lớp.');catechism(name,'homework')};

async function realGrades(name){const cid=await clsId(name),year='2026-2027',term='HK1';const ms=await clsMembers(name);const {data:items}=await sb.from('grade_items').select('id,name,category,weight,academic_term').eq('class_id',cid).eq('academic_term',`${year}|${term}`).order('name');const ids=(items||[]).map(x=>x.id);let grades=[];if(ids.length){const {data}=await sb.from('student_grades').select('id,grade_item_id,member_id,score').in('grade_item_id',ids);grades=data||[]};const can=roleWrite();return `<div class="toolbar"><select id="gradeYearReal" class="select" onchange="reloadGrade('${name}')"><option value="2026-2027">Năm 1 · 2026–2027</option><option value="2027-2028">Năm 2 · 2027–2028</option></select><select id="gradeTermReal" class="select" onchange="reloadGrade('${name}')"><option value="HK1">Học kỳ I</option><option value="HK2">Học kỳ II</option></select></div><div id="gradeRealTable">${gradeTable(ms,items||[],grades,can)}</div>`}
function gradeTable(ms,items,grades,can){const get=(mid,iid)=>grades.find(g=>g.member_id===mid&&g.grade_item_id===iid)?.score;return `<div class="table-wrap"><table class="table grade-table"><thead><tr><th>Học viên</th>${items.map(i=>`<th>${esc(i.name)}</th>`).join('')}<th>TB</th></tr></thead><tbody>${ms.map(m=>{const vals=items.map(i=>get(m.id,i.id));const nums=vals.filter(v=>v!==null&&v!==undefined).map(Number),avg=nums.length?(nums.reduce((a,b)=>a+b,0)/nums.length).toFixed(2):'—';return `<tr><td><b>${esc(m.full_name)}</b></td>${items.map((i,k)=>`<td>${can?`<input class="score-input" type="number" min="0" max="10" step="0.25" value="${vals[k]??''}" onchange="saveScore('${m.id}','${i.id}',this.value)">`:(vals[k]??'—')}</td>`).join('')}<td><b>${avg}</b></td></tr>`}).join('')||'<tr><td class="empty">Không có dữ liệu.</td></tr>'}</tbody></table></div>`}
window.reloadGrade=async function(name){const cid=await clsId(name),y=document.getElementById('gradeYearReal').value,t=document.getElementById('gradeTermReal').value,ms=await clsMembers(name);const {data:items}=await sb.from('grade_items').select('id,name,category,weight,academic_term').eq('class_id',cid).eq('academic_term',`${y}|${t}`).order('name');const ids=(items||[]).map(x=>x.id);let grades=[];if(ids.length){const {data}=await sb.from('student_grades').select('id,grade_item_id,member_id,score').in('grade_item_id',ids);grades=data||[]};document.getElementById('gradeRealTable').innerHTML=gradeTable(ms,items||[],grades,roleWrite())};
window.saveScore=async function(mid,iid,val){const score=val===''?null:Number(val);const {error}=await sb.from('student_grades').upsert({member_id:mid,grade_item_id:iid,score},{onConflict:'grade_item_id,member_id'});if(error)alert(error.message)};

async function realAttendance(name){const cid=await clsId(name),ms=await clsMembers(name),can=roleWrite();const {data:sessions}=await sb.from('attendance_sessions').select('id,session_date,session_type,title').eq('class_id',cid).order('session_date',{ascending:false}).limit(10);if(!can)return `<div class="panel"><h2>Lịch sử điểm danh</h2>${(sessions||[]).map(s=>`<div class="row"><span>${new Date(s.session_date+'T00:00').toLocaleDateString('vi-VN')} · ${esc(s.session_type)}</span><button class="secondary" onclick="viewMyAttendance('${s.id}')">Xem</button></div>`).join('')||'<div class="empty">Chưa có buổi điểm danh.</div>'}<div id="myAttendance"></div></div>`;return `<div class="toolbar"><input id="attDate" class="input" type="date" value="${new Date().toISOString().slice(0,10)}"><select id="attType" class="select"><option>Học giáo lý</option><option>Thánh lễ</option><option>Sinh hoạt đoàn</option><option>Học hát</option></select><button class="primary" onclick="startAttendance('${name}')">Mở buổi điểm danh</button></div><div id="attendanceWork"></div><div class="panel"><h2>10 buổi gần nhất</h2>${(sessions||[]).map(s=>`<div class="row"><span>${new Date(s.session_date+'T00:00').toLocaleDateString('vi-VN')} · ${esc(s.session_type)}</span><span>${esc(s.title||'')}</span></div>`).join('')||'<div class="empty">Chưa có buổi điểm danh.</div>'}</div>`}
window.startAttendance=async function(name){const cid=await clsId(name),date=document.getElementById('attDate').value,type=document.getElementById('attType').value,ms=await clsMembers(name);let {data:sess}=await sb.from('attendance_sessions').select('id').eq('class_id',cid).eq('session_date',date).eq('session_type',type).maybeSingle();if(!sess){const {data,error}=await sb.from('attendance_sessions').insert({class_id:cid,session_date:date,session_type:type,title:`${type} ${new Date(date+'T00:00').toLocaleDateString('vi-VN')}`}).select('id').single();if(error)return alert(error.message);sess=data}const {data:records}=await sb.from('attendance_records').select('member_id,present,conduct,note').eq('session_id',sess.id);document.getElementById('attendanceWork').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Học viên</th><th>Có mặt</th><th>Nề nếp</th><th>Ghi chú</th></tr></thead><tbody>${ms.map(m=>{const r=(records||[]).find(x=>x.member_id===m.id);return `<tr><td>${esc(m.full_name)}</td><td><input id="p_${m.id}" type="checkbox" ${r?.present?'checked':''}></td><td><select id="c_${m.id}" class="select small"><option value="">—</option><option ${r?.conduct==='Tốt'?'selected':''}>Tốt</option><option ${r?.conduct==='Nhắc nhở'?'selected':''}>Nhắc nhở</option></select></td><td><input id="n_${m.id}" class="input small" value="${esc(r?.note||'')}"></td></tr>`}).join('')}</tbody></table></div><div style="margin-top:12px"><button class="primary" onclick='saveAttendance("${sess.id}",${JSON.stringify(ms.map(m=>m.id))})'>Lưu điểm danh</button></div>`};
window.saveAttendance=async function(sid,mids){const rows=mids.map(mid=>({session_id:sid,member_id:mid,present:document.getElementById(`p_${mid}`).checked,conduct:document.getElementById(`c_${mid}`).value||null,note:document.getElementById(`n_${mid}`).value||null}));const {error}=await sb.from('attendance_records').upsert(rows,{onConflict:'session_id,member_id'});if(error)return alert(error.message);alert('Đã lưu điểm danh.')};
window.viewMyAttendance=async function(sid){const {data}=await sb.from('attendance_records').select('present,conduct,note').eq('session_id',sid).maybeSingle();document.getElementById('myAttendance').innerHTML=data?`<div class="footer-note">${data.present?'✅ Có mặt':'❌ Vắng'} · ${esc(data.conduct||'')} ${data.note?'· '+esc(data.note):''}</div>`:''};

window.finance=async function(){setHead('Tài chính','Thu · Chi · Chương trình · Báo cáo');if(!requireLogin()){P().innerHTML=noLogin();return}const {data,error}=await sb.from('transactions').select('*').order('transaction_date',{ascending:false});if(error){P().innerHTML='<div class="panel"><h2>Không có quyền truy cập Tài chính</h2><div class="note">Chỉ BĐH được xem và nhập dữ liệu tài chính.</div></div>';return}const thu=(data||[]).filter(x=>String(x.type).toLowerCase().includes('thu')).reduce((s,x)=>s+Number(x.amount),0),chi=(data||[]).filter(x=>String(x.type).toLowerCase().includes('chi')).reduce((s,x)=>s+Number(x.amount),0);P().innerHTML=`<div class="hero"><h1>Tài chính</h1><button class="primary" onclick="showTxnForm()">+ Thêm giao dịch</button></div><div id="txnForm"></div><div class="finance-grid"><div class="card"><div class="money positive">${thu.toLocaleString('vi-VN')} ₫</div><div class="metric-label">Tổng thu</div></div><div class="card"><div class="money negative">${chi.toLocaleString('vi-VN')} ₫</div><div class="metric-label">Tổng chi</div></div><div class="card"><div class="money">${(thu-chi).toLocaleString('vi-VN')} ₫</div><div class="metric-label">Số dư</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Ngày</th><th>Loại</th><th>Nội dung</th><th>Danh mục</th><th>Chương trình</th><th>Số tiền</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>${new Date(x.transaction_date+'T00:00').toLocaleDateString('vi-VN')}</td><td>${esc(x.type)}</td><td>${esc(x.description)}</td><td>${esc(x.category||'')}</td><td>${esc(x.program||'')}</td><td><b>${Number(x.amount).toLocaleString('vi-VN')} ₫</b></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Chưa có giao dịch.</td></tr>'}</tbody></table></div>`};
window.showTxnForm=function(){document.getElementById('txnForm').innerHTML=`<div class="panel"><div class="toolbar"><select id="txType" class="select"><option>Thu</option><option>Chi</option></select><input id="txDate" type="date" class="input" value="${new Date().toISOString().slice(0,10)}"><input id="txAmount" type="number" class="input" placeholder="Số tiền"><input id="txDesc" class="input" placeholder="Nội dung"><input id="txCat" class="input" placeholder="Danh mục"><input id="txProgram" class="input" placeholder="Chương trình"><button class="primary" onclick="saveTxn()">Lưu</button></div></div>`};
window.saveTxn=async function(){const row={type:document.getElementById('txType').value,transaction_date:document.getElementById('txDate').value,amount:Number(document.getElementById('txAmount').value),description:document.getElementById('txDesc').value.trim(),category:document.getElementById('txCat').value.trim()||null,program:document.getElementById('txProgram').value.trim()||null,created_by:TNTT.user?.id||null};if(!row.amount||!row.description)return alert('Nhập nội dung và số tiền.');const {error}=await sb.from('transactions').insert(row);if(error)return alert(error.message);finance()};

window.accounts=async function(group='Tất cả tài khoản'){setHead('Tài khoản',group);if(!requireLogin()){P().innerHTML=noLogin();return}let {data,error}=await sb.from('member_accounts').select('member_id,email,account_group,roles,auth_user_id,active,members(full_name,branch,member_type,team_role)').order('email');if(error){P().innerHTML='<div class="panel"><h2>Tài khoản của tôi</h2><div class="note">Bạn không có quyền quản lý tài khoản khác.</div></div>';return}data=data||[];if(group.includes('BĐH'))data=data.filter(x=>x.roles?.includes('bdh'));else if(group.includes('Ban Giáo lý'))data=data.filter(x=>x.roles?.includes('giao_ly_vien'));else if(group.includes('Hội đồng'))data=data.filter(x=>x.roles?.includes('hoi_dong_huynh_truong_du_truong'));else if(group.includes('Chiên Con'))data=data.filter(x=>x.members?.branch==='Chiên Con');else if(group.includes('Ấu Nhi'))data=data.filter(x=>x.members?.branch==='Ấu Nhi');else if(group.includes('Thiếu Nhi'))data=data.filter(x=>x.members?.branch==='Thiếu Nhi');else if(group.includes('Nghĩa')||group.includes('Hiệp'))data=data.filter(x=>x.members?.branch==='Nghĩa sĩ & Hiệp sĩ');P().innerHTML=`<div class="hero"><div><h1>${esc(group)}</h1><div class="muted">${data.length} tài khoản</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Thành viên</th><th>Tài khoản</th><th>Nhóm quyền</th><th>Vai trò hệ thống</th><th>Trạng thái</th></tr></thead><tbody>${data.map(a=>`<tr><td><b>${esc(a.members?.full_name||'')}</b></td><td>${esc(a.email)}</td><td>${esc(a.account_group)}</td><td>${esc((a.roles||[]).join(' · '))}</td><td><span class="pill ${a.auth_user_id?'green':'blue'}">${a.auth_user_id?'Đã kích hoạt':'Chưa kích hoạt'}</span></td></tr>`).join('')}</tbody></table></div>`};

window.addEventListener('tntt-auth-changed',()=>{if(TNTT.user&&document.getElementById('pageTitle')?.textContent==='Tổng quan Xứ đoàn')dashboard()});
})();
